version: '3'

services:

  redis:
    image: redis:latest
    expose:
      - 6379

  postgres:
    image: postgres:latest
    volumes:
      - postgres_data_volume:/var/lib/postgresql/data/
    env_file:
      - ./config/.env.prod.db
    expose:
      - 5432

volumes:
  postgres_data_volume: